backend_dev/protected/models/Box.php
<?php

/**
 * This is the model class for table "box".
 *
 * The followings are the available columns in table 'box':
 * @property integer $id
 * @property string $nazvanie
 * @property string $opisanie
 * @property integer $object_id
 * @property integer $status_id
 * @property string $data_sozdaniya
 * @property integer $avtor_zapisi_id
 * @property string $data_zapisi
 */
class Box extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'box';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			//array('data_sozdaniya, data_zapisi', 'required'),
			array('object_id, status_id, avtor_zapisi_id', 'numerical', 'integerOnly'=>true),
			array('nazvanie', 'length', 'max'=>30),
			array('opisanie', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, nazvanie, opisanie, object_id, status_id, data_sozdaniya, avtor_zapisi_id, data_zapisi', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
        return array(
            'object' => array(self::BELONGS_TO, 'Object', 'object_id'),
		    'status' => array(self::BELONGS_TO, 'BoxStatus', 'status_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nazvanie' => 'Название',
			'opisanie' => 'Описание',
			'object_id' => 'Object',
			'status_id' => 'Статус',
			'data_sozdaniya' => 'Data Sozdaniya',
			'avtor_zapisi_id' => 'Avtor Zapisi',
			'data_zapisi' => 'Data Zapisi',
                        'status.nazvanie'=>'Статус',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
        
     //   public $status_id='';
        
        public function getDayDropDown()
            {
          
           return CHtml::dropDownList('box_status',$this->status_id,BoxStatus::model()->getForFilter()
               ,array('class'=>'box_status', 'id'=>$this->id)
            );
       //         return BoxStatus::model()->getDropDown();
            }

        
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;
                
               // $criteria->with = array('status');
               // $criteria->together = true;
                
		$criteria->compare('t.id',$this->id);
		$criteria->compare('t.nazvanie',$this->nazvanie,true);
		$criteria->compare('t.opisanie',$this->opisanie,true);
		$criteria->compare('t.object_id',$this->object_id);
		$criteria->compare('t.status_id',$this->status_id);
		$criteria->compare('t.data_sozdaniya',$this->data_sozdaniya,true);
		$criteria->compare('t.avtor_zapisi_id',$this->avtor_zapisi_id);
		$criteria->compare('t.data_zapisi',$this->data_zapisi,true);
              //  $criteria->compare('status.id',$this->status,true);
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Box the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

backend_dev/protected/controllers/BoxController.php
<?php

class BoxController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'ChangeStatus'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'UpdateZnachenie'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'UpdateZnachenie'),
                'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionUpdateZnachenie()
    {
        $es = new TbEditableSaver('Box');
        $es->update();
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionChangeStatus()
    {
        //    if (isset($_POST['Box'])){
        //       $model=$this->loadModel($_POST['Box']);
        //         $model->status_id=$_POST['status_id'];
        // var_dump($_POST['status_id']);
        //     }
        $model = $this->loadModel($_POST['id_box']);
        $model->status_id = $_POST['id_stat'];
        $model->save();
        //    echo $_POST['id_box'];
        //   echo $_POST['id_stat'];
        //  exit;

    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Box;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Box'])) {
            $model->attributes = $_POST['Box'];
            if ($model->save())
                $this->redirect(array('/object/'.$model->object_id."?tab=6"));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Box'])) {
            $model->attributes = $_POST['Box'];
            if ($model->save())
                $this->redirect(array('/object/' . $model->object_id."?tab=6"));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Box');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin($id)
    {
        $model = new Box('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['Box']))
            $model->attributes = $_GET['Box'];
        $model->object_id = $id;
        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model = Box::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'box-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

backend_dev/protected/views/box/_form.php
<div class="alert alert-info glyphicon-info-sign">Поля, отмеченные <span class="required">*</span> обязательны к
    заполнению.
</div>

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'box-form',
    'htmlOptions' => array('class' => 'well'),
    'enableAjaxValidation' => false,
    'focus' => array($model, 'nazvanie'),
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldRow($model, 'nazvanie', array('class' => 'span5', 'maxlength' => 30)); ?>

<?php echo $form->textAreaRow($model, 'opisanie', array('rows' => 6, 'cols' => 50, 'class' => 'span8')); ?>

<?php echo $form->hiddenField($model, 'object_id'); ?>

<div class="row2">
    <?php echo $form->labelEx($model, 'Статус'); ?>
    <?php echo $form->dropDownList($model, 'status_id', BoxStatus::model()->getForFilter()); ?>
    <?php echo $form->error($model, 'status_id'); ?>
</div>

<?php echo $form->hiddenField($model, 'avtor_zapisi_id'); ?>

<hr/>
<?php $this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'submit',
    'icon' => 'check white',
    'type' => 'primary',
    'label' => $model->isNewRecord ? 'Создать' : 'Сохранить',
)); ?>

<?
$this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'button',
    'type' => 'danger',
    'icon' => 'remove white',
    'label' => 'Отмена',
    'htmlOptions' => array(
        'onClick' => "window.location.href = '/object/view/" . $model->object_id . "?tab=6'",
    )
));
?>

<?php $this->endWidget(); ?>

backend_dev/protected/views/box/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'nazvanie',array('class'=>'span5','maxlength'=>30)); ?>

	<?php echo $form->textAreaRow($model,'opisanie',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'object_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'status_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'data_sozdaniya',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'avtor_zapisi_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'data_zapisi',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Найти',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

backend_dev/protected/views/box/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nazvanie')); ?>:</b>
	<?php echo CHtml::encode($data->nazvanie); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('opisanie')); ?>:</b>
	<?php echo CHtml::encode($data->opisanie); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('object_id')); ?>:</b>
	<?php echo CHtml::encode($data->object_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status_id')); ?>:</b>
	<?php echo CHtml::encode($data->status_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('data_sozdaniya')); ?>:</b>
	<?php echo CHtml::encode($data->data_sozdaniya); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('avtor_zapisi_id')); ?>:</b>
	<?php echo CHtml::encode($data->avtor_zapisi_id); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('data_zapisi')); ?>:</b>
	<?php echo CHtml::encode($data->data_zapisi); ?>
	<br />

	*/ ?>

</div>

backend_dev/protected/views/box/admin.php
<?php

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('box-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
$url = $this->createUrl('box/ChangeStatus');
?>
<script>
    $(document).ready(function () {
        $('.box_status').change(function () {

            $.post('<?php echo $url ?>',
                {
                    id_box: $(this).attr('id'),
                    id_stat: $(this).val()
                });
        });
    });
</script>
<div class="page-header">
    <h1>Боксы
        <?php
        $this->widget('bootstrap.widgets.TbButtonGroup', array(
            'buttons' => array(
                array('buttonType' => 'link', 'type' => 'success', 'icon' => 'plus white', 'url' => '/box/create/'.$model->object_id),
                array('buttonType' => 'link', 'type' => 'primary', 'icon' => 'search white', 'url' => '#', 'htmlOptions' => array('class' => 'search-button')),
            )));
        ?>
    </h1>
</div>

<div class="search-form" style="display:none">
    <?php $this->renderPartial('_search', array(
        'model' => $model,
    )); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'box-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        array(
            'name' => 'nazvanie',
            'class' => 'bootstrap.widgets.TbEditableColumn',
            'editable' => array(
                'url' => '/Box/UpdateZnachenie',
            ),
        ),
        array(
            'name' => 'opisanie',
            'class' => 'bootstrap.widgets.TbEditableColumn',
            'editable' => array(
                'url' => '/Box/UpdateZnachenie',
            ),
        ),
        array(
            'name' => 'status_id',
            'class' => 'bootstrap.widgets.TbEditableColumn',
            'filter' => CHtml::listData(BoxStatus::model()->findAll(), "id", "nazvanie"),
            'value' => '$data->status->nazvanie',
            'editable' => array(
                'type' => 'select',
                'source' => CHtml::listData(BoxStatus::model()->findAll(), "id", "nazvanie"),
                'url' => '/Box/UpdateZnachenie',
            ),
        ),
        array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{delete}',
            'buttons' => array
            (
                'delete' => array
                (
                    'url' => 'Yii::app()->createUrl("/box/delete", array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'btn-column',
                    ),
                ),
            ),
        ),
    ),
)); ?>

backend_dev/protected/views/box/create.php
<?php
$model->object_id = $_GET['id'];
$this->breadcrumbs = array(
    'Контрагенты' => '/kontragent/',
    $model->object->kontragenty->nazvanie => array('/kontragent/' . $model->object->kontragenty->id),
    'Объекты' => array("/kontragent/{$model->object->kontragenty->id}?tab=3"),
    $model->object->nazvanie => array("/object/view/" . $model->object->id),
    'Боксы' => array("/object/view/" . $model->object->id . "?tab=6"),
    'Новый'
);
?>

    <div class="page-header">
        <h1>Новый бокс</h1>
    </div>

<?
$model->object_id = $_GET['id'];
$model->avtor_zapisi_id = Yii::app()->user->id;
?>
<?php echo $this->renderPartial('_form', array('model' => $model)); ?>

backend_dev/protected/views/box/index.php
<?php
$this->breadcrumbs=array(
	'Boxes',
);

$this->menu=array(
	array('label'=>'Create Box','url'=>array('create')),
	array('label'=>'Manage Box','url'=>array('admin')),
);
?>

<h1>Boxes</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

backend_dev/protected/views/box/update.php
<?php
$this->breadcrumbs = array(
    'Контрагенты' => '/kontragent/',
    $model->object->kontragenty->nazvanie => array('/kontragent/' . $model->object->kontragenty->id),
    'Объекты' => array("/kontragent/{$model->object->kontragenty->id}?tab=3"),
    $model->object->nazvanie => array("/object/view/" . $model->object->id),
    'Боксы' => array("/object/view/" . $model->object->id . "?tab=6"),
    $model->nazvanie
);
?>

    <div class="page-header">
        <h1>Редактор бокса &laquo;<?=$model->nazvanie?>&raquo;</h1>
    </div>


<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

backend_dev/protected/views/box/view.php
<?php
$this->breadcrumbs=array(
	'Boxes'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Box','url'=>array('index')),
	array('label'=>'Create Box','url'=>array('create')),
	array('label'=>'Update Box','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Box','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Box','url'=>array('admin')),
);
?>

<h1>View Box #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'nazvanie',
		'opisanie',
		'object_id',
		'status_id',
		'data_sozdaniya',
		'avtor_zapisi_id',
		'data_zapisi',
	),
)); ?>