backend_dev/protected/controllers/ObjectController.php
<?php

class ObjectController extends Controller
{

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('ViewForClient', 'getVremyaCombo'),
                'roles' => array('client'),
            ),
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'ObjectByAgent', 'savecoords', 'sampleOfObj', 'androidGetList', 'admin'),
                'roles' => array('manager'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'UpdateZnachenie', 'delete'),
                'roles' => array('owner'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionGetVremyaCombo($object_id, $resource, $interval)
    {
        $data = "CURRENT_DATE() + INTERVAL $interval DAY";
        $sql = "
SELECT id, box_id, SUBSTR(vremya,1,5) AS vremya
FROM object_resource_view
WHERE object_id=$object_id AND `data`=$data AND resource>=$resource
";
        $mdl = ObjectResourceView::model()->findAllBySql($sql);
        $list = '[';
        foreach ($mdl AS $row) {
            $list .= '{"id":"' . $row->id . '","text":"' . $row->vremya . '"},';
        }
        $list .= '{"id":"0", "text":"----"}]';
        echo $list;
    }

    public function actionUpdateZnachenie()
    {
        $es = new TbEditableSaver('Object');
        $es->update();
    }

    public function actionGetFreeTime($objectId, $data, $resource)
    {

    }

    public function actionViewForClient($object_id = null, $uslugi = null, $car_id = null, $data = null)
    {
        if ($object_id == null)
            return;
        $model = $this->loadModel($object_id);
        $this->renderPartial('viewForClient', array('model' => $model, 'uslugi' => $uslugi, 'car_id' => $car_id, 'data' => $data));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model = Object::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {

        $model = $this->loadModel($id);
        $this->render('view', array(
            'model' => $model,
            'gMap' => $this->prepareGmap($this->loadModel($id)),
            'kontragent' => Kontragent::model()->findByPk($model->kontragent_id),
        ));
    }

    protected function prepareGmap($model)
    {
//
// ext is your protected.extensions folder
// gmaps means the subfolder name under your protected.extensions folder
//
        Yii::import('ext.EGMap.*');

        $gMap = new EGMap();
        $gMap->setWidth('100%');
        $gMap->setHeight(550);
        $gMap->zoom = 10;
        $mapTypeControlOptions = array(
            'position' => EGMapControlPosition::RIGHT_TOP,
            'style' => EGMap::MAPTYPECONTROL_STYLE_HORIZONTAL_BAR
        );

        $gMap->mapTypeId = EGMap::TYPE_ROADMAP;
        $gMap->mapTypeControlOptions = $mapTypeControlOptions;

// Preparing InfoWindow with information about our marker.
        $info_window_a = new EGMapInfoWindow("<div class='gmaps-label' style='color: #000;'>{$model->nazvanie}</div>");

// Setting up an icon for marker.
        $icon = new EGMapMarkerImage("http://google-maps-icons.googlecode.com/files/car.png");

        $icon->setSize(32, 37);
        $icon->setAnchor(16, 16.5);
        $icon->setOrigin(0, 0);

// Saving coordinates after user dragged our marker.
        $dragevent = new EGMapEvent('dragend', "function (event) { $.ajax({
                                            'type':'POST',
                                            'url':'" . $this->createUrl('object/saveCoords') . '/' . $model->id . "',
                                            'data':({'lat': event.latLng.lat(), 'lng': event.latLng.lng()}),
                                            'cache':false,
                                        });}", false, EGMapEvent::TYPE_EVENT_DEFAULT);


// If we have already created marker - show it
        if ($model->havemap != 0) {
            $sample_address = $model->gorod->nazvanie . ', ' . $model->adres;
            $geocoded_address = new EGMapGeocodedAddress($sample_address);
            $geocoded_address->geocode($gMap->getGMapClient());

            if ($geocoded_address->getLat() != NULL && $geocoded_address->getLng() != NULL) {
                $gMap->addMarker(
                    new EGMapMarker($geocoded_address->getLat(), $geocoded_address->getLng(), array())
                );
            }

            $marker = new EGMapMarkerWithLabel($model->lat, $model->lon, array('title' => Yii::t('object', $model->nazvanie),
                'icon' => $icon, 'draggable' => true), 'marker', array('dragevent' => $dragevent));
            $marker->addHtmlInfoWindow($info_window_a);

            $label_options = array(
                'backgroundColor' => 'black',
                'padding' => '5px',
                'opacity' => '0.65',
                'width' => 'auto',
                'color' => 'white'
            );
            $marker->labelContent = "<strong>{$model->nazvanie}</strong><br/>$model->adres";
            $marker->labelStyle = $label_options;

            $marker->setLabelAnchor(new EGMapPoint(-15, 15));


            $gMap->addMarker($marker);
            $gMap->setCenter($model->lat, $model->lon);
            $gMap->zoom = 16;

// If we don't have marker in database - make sure user can create one
        } else {
            $gorod = Gorod::model()->findByPk($model->gorod_id);
            $gMap->setCenter($gorod->lat, $gorod->lon);
            $gMap->zoom = 16;
            // Setting up new event for user click on map, so marker will be created on place and respectful event added.
            $gMap->addEvent(new EGMapEvent('click', 'function (event) {var marker = new google.maps.Marker({position: event.latLng, map: ' . $gMap->getJsName() .
                ', draggable: true, icon: ' . $icon->toJs() . '}); ' . $gMap->getJsName() .
                '.setCenter(event.latLng); var dragevent = ' . $dragevent->toJs('marker') .
                '; $.ajax({' .
                '"type":"POST",' .
                '"url":"' . $this->createUrl('object/savecoords') . "/" . $model->id . '",' .
                '"data":({"lat": event.latLng.lat(), "lng": event.latLng.lng()}),' .
                '"cache":false,' .
                '}); }', false, EGMapEvent::TYPE_EVENT_DEFAULT_ONCE));
        }
        return $gMap;
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate($id)
    {
        $model = new Object;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Object'])) {
            $model->attributes = $_POST['Object'];
            $model->avtor_zapisi_id = Yii::app()->user->id;
            $model->kontragent_id = $id;
            if ($model->save())
                $this->redirect(array('/object/view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
            'grafik' => GrafikRaboty::model()->getForFilter($id),
            'gorod' => Gorod::model()->getForFilter(),
            'kontragent' => Kontragent::model()->findByPk($id),
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Object'])) {
            $model->attributes = $_POST['Object'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
            'grafik' => GrafikRaboty::model()->getForFilter($model->kontragent_id),
            'gorod' => Gorod::model()->getForFilter(),
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))

backend_dev/protected/views/object/_form.php
<div class="alert alert-info glyphicon-info-sign">Поля, отмеченные <span class="required">*</span> обязательны к
    заполнению.
</div>

<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'object-form',
    'htmlOptions' => array('class' => 'well'),
    'enableAjaxValidation' => false,
    'focus'=>array($model,'nazvanie'),
));
?>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldRow($model, 'nazvanie', array('class' => 'span5', 'maxlength' => 100)); ?>

<?php echo $form->textAreaRow($model, 'adres', array('rows' => 2, 'class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'telefon', array('maxlength' => 30)); ?>

<div class="row2">
    <?php echo $form->labelEx($model, 'Город'); ?>
    <?php echo $form->dropDownList($model, 'gorod_id', $gorod, array('prompt' => '(Укажите город)'));
    ?>
    <?php echo $form->error($model, 'gorod_id'); ?>
</div>

<div class="row2">
    <?php echo $form->labelEx($model, 'График работы'); ?>
    <?php echo $form->dropDownList($model, 'grafik_raboty_id', $grafik, array('prompt' => '(Укажите график)'));
    ?>
    <?php echo $form->error($model, 'grafik_raboty_id'); ?>
</div>

<?php echo $form->textFieldRow($model, 'zarplata'); ?>

<hr/>
<?php
$this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'submit',
    'type' => 'primary',
    'icon' => 'check white',
    'label' => $model->isNewRecord ? 'Создать' : 'Сохранить',
));
?>

<?
$this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'button',
    'type' => 'danger',
    'icon' => 'remove white',
    'label' => 'Отмена',
    'htmlOptions' => array(
        'onClick' => "window.location.href = '/kontragent/view/" . @$_GET['id'] . "?tab=3'",
    )
));
?>

<?php $this->endWidget(); ?>

backend_dev/protected/views/object/_search.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'action' => Yii::app()->createUrl($this->route),
    'method' => 'get',
        ));
?>

<?php echo $form->textFieldRow($model, 'id', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'nazvanie', array('class' => 'span5', 'maxlength' => 100)); ?>

<?php echo $form->textAreaRow($model, 'adres', array('rows' => 6, 'cols' => 50, 'class' => 'span8')); ?>

<?php echo $form->textFieldRow($model, 'telefon', array('class' => 'span5', 'maxlength' => 30)); ?>

<?php echo $form->textFieldRow($model, 'grafik_raboty_id', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'zarplata', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'data_sozdaniya', array('class' => 'span5')); ?>

<?php echo $form->textFieldRow($model, 'avtor_zapisi_id', array('class' => 'span5')); ?>

    <?php echo $form->textFieldRow($model, 'data_zapisi', array('class' => 'span5')); ?>

<div class="form-actions">
    <?php
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'primary',
        'label' => 'Найти',
    ));
    ?>
</div>

<?php $this->endWidget(); ?>

backend_dev/protected/views/object/_view.php
<div class="view">

    <b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
    <?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('nazvanie')); ?>:</b>
    <?php echo CHtml::encode($data->nazvanie); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('adres')); ?>:</b>
    <?php echo CHtml::encode($data->adres); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('telefon')); ?>:</b>
    <?php echo CHtml::encode($data->telefon); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('grafik_raboty_id')); ?>:</b>
    <?php echo CHtml::encode($data->grafik_raboty_id); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('zarplata')); ?>:</b>
    <?php echo CHtml::encode($data->zarplata); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('data_sozdaniya')); ?>:</b>
    <?php echo CHtml::encode($data->data_sozdaniya); ?>
    <br />

    <?php /*
      <b><?php echo CHtml::encode($data->getAttributeLabel('avtor_zapisi_id')); ?>:</b>
      <?php echo CHtml::encode($data->avtor_zapisi_id); ?>
      <br />

      <b><?php echo CHtml::encode($data->getAttributeLabel('data_zapisi')); ?>:</b>
      <?php echo CHtml::encode($data->data_zapisi); ?>
      <br />

     */ ?>

</div>

backend_dev/protected/views/object/admin.php
<?php
$this->breadcrumbs = array(
    'Объекты'
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('object-grid', {
		data: $(this).serialize()
	});
	return false;
}); 
");
?>
    <script>
        $(document).ready(function () {
            $('#object-grid tbody tr').live('dblclick', function () {
                var id = $.fn.yiiGridView.getKey(
                    'object-grid',
                    $(this).prevAll().length
                );
                document.location.href = '/object/' + id;
            });
        });
    </script>
    <div class="page-header">
        <h1>Объекты
            <?php
              Yii::app()->user->checkAccess('owner')?
            $this->widget('bootstrap.widgets.TbButtonGroup', array(              
                'buttons' => array(
                    array('buttonType' => 'link', 'type' => 'success', 'icon' => 'plus white', 'url' => '/object/create/' . $model->kontragent_id),
                    array('buttonType' => 'link', 'type' => 'primary', 'icon' => 'search white', 'url' => '#', 'htmlOptions' => array('class' => 'search-button')),
                ))):
                 $this->widget('bootstrap.widgets.TbButtonGroup', array(              
                'buttons' => array(               
                    array('buttonType' => 'link', 'type' => 'primary', 'icon' => 'search white', 'url' => '#', 'htmlOptions' => array('class' => 'search-button')),
                )));  
            ?>
        </h1>
    </div>

    <div class="search-form" style="display:none">
        <div class="alert alert-info glyphicon-info-sign">
            В фильтрах можно использовать знаки сравнения (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
            или равенства <b>=</b>), указав их перед выражением.
        </div>
        <?php
        $this->renderPartial('_search', array(
            'model' => $model,
        ));
        ?>
    </div><!-- search-form -->
<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'object-grid',
    'dataProvider' => $dp,
    'filter' => $model,
    'columns' => array(
      //  array('name' => 'id', 'htmlOptions' => array('style' => 'width:20px; text-align:center')),
        'id',
        array('name' => 'nazvanie', 'type'=>'raw', 'value'=>'$data->nazvanie'),
        //'nazvanie',
        
        'adres',
        'telefon',
        'gorod.nazvanie',
        //'grafik_raboty_id',
        //'zarplata',
        /*
          'data_sozdaniya',
          'avtor_zapisi_id',
          'data_zapisi',
         */
        array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{view} {delete}',
            'buttons' => array
            (
                'view' => array
                (
                    'url' => 'Yii::app()->createUrl("/object/view", array("id"=>$data->id))',
                ),
                'delete' => array
                (
                    'url' => 'Yii::app()->createUrl("/object/delete", array("id"=>$data->id))',
                    'options' => array(
                        'class' => 'btn-column',
                    ),
                ),
            ),
        ),
    ),
));
?>

backend_dev/protected/views/object/adminForClient.php
<div class="span4">
    <?php
    $this->widget('bootstrap.widgets.TbGridView', array(
        'id' => 'object-grid',
        'dataProvider' => $dataProvider,
        'filter' => $model,
        'hideHeader' => true,
        'type' => 'striped',
        'columns' => array(
            array(
                'name' => 'nazvanie',
                'type' => 'raw',
                'value' => '"<strong><nobr>".$data->nazvanie."</nobr></strong><br/>".$data->adres'
            )
        ),
    ));
    ?>
</div>
<div class="span8 well" style="height: 100%;" id="objectInfo">
    <br/>
    <h4 class="icon-arrow-left"> Для поиска мойки по названию используйте фильтр</h4>
    <br/><br/><br/>
    <h4 class="icon-arrow-left"> Выберите мойку из списка</h4>
</div>

backend_dev/protected/views/object/create.php
<?php
$this->breadcrumbs = array(
    'Контрагенты' => array('/kontragent/admin/'),
    $kontragent->nazvanie => array('/kontragent/view/' . $kontragent->id),
    'Объекты' => array('/kontragent/view/' . $kontragent->id."?tab=3"),
    'Новый',
);
?>
<div class="page-header">
    <h1>Новый объект</h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model, 'grafik' => $grafik, 'gorod' => $gorod)); ?>

backend_dev/protected/views/object/index.php
<?php
$this->breadcrumbs = array(
    'Объекты',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('object-grid', {
		data: $(this).serialize()
	});
	return false;
});
$(document).ready(function() {
    $('#object-grid tbody tr').live('dblclick', function() {
        var id = $.fn.yiiGridView.getKey(
                'object-grid',
                $(this).prevAll().length
                );
        document.location.href = '/object/' + id;
    });
});
");
?>


<div class="page-header">
    <h1>Объекты
        <?php
        $this->widget('bootstrap.widgets.TbButton', array('buttonType' => 'link', 'size'=>'mini', 'type' => 'primary', 'icon' => 'glyphicon glyphicon-search', 'url' => '#', 'htmlOptions' => array('class' => 'search-button'))
        );
        ?>
    </h1>
</div>

<div class="search-form" style="display:none">
    <div class="alert alert-info glyphicon-info-sign">
        В фильтрах можно использовать знаки сравнения (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
            &lt;&gt;</b>
        или равенства <b>=</b>), указав их перед выражением.
    </div>
    <?php
    $this->renderPartial('_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'id' => 'object-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        array('name' => 'id', 'htmlOptions' => array('style' => 'width:20px; text-align:center')),
        'nazvanie',
        'adres',
        'telefon',
        //'grafik_raboty_id',
        //'zarplata',
        /*
          'data_sozdaniya',
          'avtor_zapisi_id',
          'data_zapisi',
         */
        array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{view} {delete}'
        ),
    ),
));
?>

backend_dev/protected/views/object/info.php
<?php
$this->widget('TbEditableDetailView', array(
    'data' => $model,
    'url' => $this->createUrl('/object/UpdateZnachenie'),
    'attributes' => array(
        'id',
        'nazvanie',
        'adres',
        'telefon',
        array(
            'name' => 'grafik_raboty_id',
            'editable' => array(
                'type' => 'select',
                'source' => CHtml::listData(GrafikRaboty::model()->findAllByAttributes(array("kontragent_id" => $model->kontragent_id)), 'id', 'nazvanie')
            )
        ),
        array(
            'name' => 'gorod_id',
            'editable' => array(
                'type' => 'select',
                'source' => CHtml::listData(Gorod::model()->findAll(), 'id', 'nazvanie')
            )
        ),
        'zarplata',
    ),
));
?>

backend_dev/protected/views/object/map.php
<?php
$gMap->renderMap();
?>

backend_dev/protected/views/object/objByUser.php
<?php
$this->breadcrumbs=array(
	'Objects'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List object','url'=>array('index')),
	array('label'=>'Create object','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('object-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Objects</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'object-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'nazvanie',
		'adres',
		'telefon',
		'grafik_raboty_id',
		'zarplata',
		/*
		'data_sozdaniya',
		'avtor_zapisi_id',
		'data_zapisi',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

backend_dev/protected/views/object/query_admin.php
<?php error_reporting(E_ALL);
 ini_set('display_errors', 'on');?>
<?php


//print_r($model);
//exit;

$this->breadcrumbs=array(
	'Objects'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List object','url'=>array('index')),
	array('label'=>'Create object','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('object-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Objects</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php 
$this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'object-grid',
	'dataProvider'=>$dp,
	'filter'=>$model,
	'columns'=>array(
		'id',
		//'nazvanie',
            
                         
		'adres',
		'telefon',
		'grafik_raboty_id',
            array(
                        'name'=>'name',
                       'type' => 'raw',
                        'value'=>'$data->nazvanie',                                          
                     
                ),
		//'administrator_id',
		/*
		'zarplata',
		'data_sozdaniya',
		'avtor_zapisi_id',
		'data_zapisi',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); 




?>
<?php error_reporting(E_ALL);
 ini_set('display_errors', 'on');?>

backend_dev/protected/views/object/update.php
<?php
$this->breadcrumbs = array(
    'Объекты' => array('admin'),
    $model->nazvanie => array('view', 'id' => $model->id),
    'Редактор',
);
?>

<div class="page-header">
    <h1>Редактор <?php echo $model->nazvanie; ?></h1>
</div>


<?php echo $this->renderPartial('_form', array('model' => $model, 'grafik' => $grafik, 'gorod' => $gorod)); ?>